### PR TITLE
Use recursively determined fieldSerializer when looking up field update serializers.

### LINKED ISSUE #98: Fields with same name at different levels of document and different serialisers can cause ClassCastException on update
A class with attributes of the same name in the root and an inner class like:

```java
public class Outer {
    public long timestamp;
    public static class Inner {
        public Date timestamp;
    }
}
```
causes a ClassCastException during serialization on updates like:

```java
collection.update(<query>, DBUpdate.set("inner.timestamp", new Date());
```
This happens because when a serializer for the inner attribute is located as the tree of bean serializers is walked the top level serializer rather than the current level serializer is used to do the field update serializer lookup. Consequently the root field is found and it's serializer is used. In the above case the Date is attempted to be serialized as a Long and ClassCastException.

Full source of example:

```java
package bugs.mongojack;

import java.time.Instant;
import java.util.Date;

import org.mongojack.DBUpdate;
import org.mongojack.Id;
import org.mongojack.JacksonDBCollection;
import org.mongojack.WriteResult;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.mongodb.DB;
import com.mongodb.MongoClient;
import com.mongodb.ServerAddress;
import com.mongodb.WriteConcern;

public class Outer {
	public static class Inner {
		@JsonProperty
		private Date timestamp;

		public Inner() {
		}
		
		public Inner(Date timestamp) {
			setTimestamp(timestamp);
		}

		public Date getTimestamp() {
			return timestamp;
		}

		public void setTimestamp(Date timestamp) {
			this.timestamp = timestamp;
		}
	}

	@Id
	private String id;

	@JsonProperty
	private long timestamp;

	@JsonProperty
	private Inner inner;
	
	public Outer() {
	}
	
	public Outer(String id, long timestamp, Inner inner) {
		setId(id);
		setTimestamp(timestamp);
		setInner(inner);
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public long getTimestamp() {
		return timestamp;
	}

	public void setTimestamp(long timestamp) {
		this.timestamp = timestamp;
	}


	public Inner getInner() {
		return inner;
	}

	public void setInner(Inner inner) {
		this.inner = inner;
	}

	public static void main(String... args) throws Exception {
		MongoClient mongoClient;
		
		mongoClient = new MongoClient(new ServerAddress("127.0.0.1", 27017));
		mongoClient.setWriteConcern(WriteConcern.JOURNAL_SAFE);

		DB db = mongoClient.getDB("bugdb");
		JacksonDBCollection<Outer, String> collection = JacksonDBCollection.wrap(db.getCollection("bug"), Outer.class, String.class);
		
		Date d_1 = Date.from(Instant.ofEpochMilli(10000));
		Date d_2 = Date.from(Instant.ofEpochMilli(20000));
		long t_1 = 30000;
		String id_1 = "1";

		Outer.Inner inner = new Outer.Inner(d_1);
		Outer test =  new Outer(id_1, t_1, inner);

		collection.removeById(id_1);
		collection.insert(test);
		
		WriteResult<Outer, String> result = collection.updateById(id_1, DBUpdate.set("inner.timestamp", d_2));
		if (result.getN() != 1) {
			System.out.println("Didn't updated document???");
		}
		Outer updated = collection.findOneById(id_1);
		
		if (updated.getTimestamp() == t_1 && updated.getInner().getTimestamp().equals(d_2)) {
			System.out.println("Update successful");
		}
		else {
			System.out.println("Update FAILED.");
		}
	}
}
```

### PR DESCRIPTION
**Pull request by tbartley**
Use recursively determined fieldSerializer when looking up field update serializers. Closes #98.

### CODE REVIEW

**Comment by benmccann** [comment]
Thanks @tbartley! Could you add a test for this fix before we merge?

**Comment by tbartley** [comment]
No problem. Will do.

Sent from my iPhone

On 17 Mar 2015, at 8:04 am, Ben McCann <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks @tbartley<https://github.com/tbartley>! Could you add a test for this fix before we merge?

-

**Comment by tbartley** [comment]
Unit test is now there.

File: src/test/java/org/mongojack/TestDBUpdateSerialization.java [hunk 1]
```diff
@@ -182,4 +206,71 @@ public void serialize(String value, JsonGenerator jgen,
...
+					if (other.timestamp != null)
+						return false;
+				} else if (!timestamp.equals(other.timestamp))
+					return false;
+				return true;
+			}
+    	}
+    	public String _id = "id";
+    	public Inner inner = new Inner();
+    	public long  timestamp;
```
Comment (benmccann) [inline src/test/java/org/mongojack/TestDBUpdateSerialization.java]: duplicate space after `long`

File: src/test/java/org/mongojack/TestDBUpdateSerialization.java [hunk 2]
```diff
@@ -182,4 +206,71 @@ public void serialize(String value, JsonGenerator jgen,
...
+				return true;
+			if (obj == null)
+				return false;
+			if (getClass() != obj.getClass())
+				return false;
+			NestedRepeatedAttributeName other = (NestedRepeatedAttributeName) obj;
+			if (_id == null) {
+				if (other._id != null)
+					return false;
+			} else if (!_id.equals(other._id))
```
Comment (benmccann) [inline src/test/java/org/mongojack/TestDBUpdateSerialization.java]: please put curly braces on this and the other `else if` clause to make it easier to read

File: src/test/java/org/mongojack/TestDBUpdateSerialization.java [hunk 3]
```diff
@@ -182,4 +206,71 @@ public void serialize(String value, JsonGenerator jgen,
...
+			}
+    	}
+    	public String _id = "id";
+    	public Inner inner = new Inner();
+    	public long  timestamp;
+		@Override
+		public int hashCode() {
+			final int prime = 31;
+			int result = 1;
+			result = prime * result + ((_id == null) ? 0 : _id.hashCode());
```
Comment (benmccann) [inline src/test/java/org/mongojack/TestDBUpdateSerialization.java]: no need for parens in `(_id == null)`.  same with the ternary operator on the next line

File: src/test/java/org/mongojack/TestDBUpdateSerialization.java [hunk 4]
```diff
@@ -182,4 +206,71 @@ public void serialize(String value, JsonGenerator jgen,
             }
         }
     }
+    
+    public static class NestedRepeatedAttributeName {
+    	public static class Inner {
+    		public Date timestamp;
+
+			@Override
+			public int hashCode() {
```
Comment (benmccann) [inline src/test/java/org/mongojack/TestDBUpdateSerialization.java]: are the hashCode and equals necessary? you don't have them in the example in https://github.com/devbliss/mongojack/issues/98

File: src/test/java/org/mongojack/TestDBUpdateSerialization.java [hunk 5]
```diff
@@ -153,6 +156,27 @@ public void testSimpleMap() {
         assertThat(coll.findOneById("id").map, equalTo(map));
     }
 
+    // Test to detect presence of issue #98
+    @Test
+    public void testUpdateOfNestedRepeatedAttributeName() {
+        coll2 = getCollection(NestedRepeatedAttributeName.class, String.class);
+
+        Calendar cal = Calendar.getInstance();
```
Comment (benmccann) [inline src/test/java/org/mongojack/TestDBUpdateSerialization.java]: this line and the next are inconsistently spaced

File: src/test/java/org/mongojack/TestDBUpdateSerialization.java [hunk 6]
```diff
@@ -153,6 +156,27 @@ public void testSimpleMap() {
         assertThat(coll.findOneById("id").map, equalTo(map));
     }
 
+    // Test to detect presence of issue #98
```
Comment (benmccann) [inline src/test/java/org/mongojack/TestDBUpdateSerialization.java]: please put a link to https://github.com/devbliss/mongojack/issues/98 instead of just saying "issue #98". this repo has lived in different places and may move again soon, so saying #98 isn't sufficiently clear

File: src/test/java/org/mongojack/TestDBUpdateSerialization.java (hunk 4 above)
Comment (tbartley) [inline src/test/java/org/mongojack/TestDBUpdateSerialization.java]: Ugly autogenerated ones from eclipse. I'll just remove them and do attribute comparison after the fetch for validation. Easier to maintain anyway.

**Comment by tbartley** [comment]
Thanks for the comments @benmccann - how does that look now?

**Comment by benmccann** [comment]
@tbartley thanks! this PR is looking really good!  a couple last minor comments...

File: src/test/java/org/mongojack/TestDBUpdateSerialization.java [hunk 7]
```diff
@@ -153,6 +157,30 @@ public void testSimpleMap() {
...
     }
 
+    // Test to detect presence of issue https://github.com/devbliss/mongojack/issues/98
+    @Test
+    public void testUpdateOfNestedRepeatedAttributeName() {
+        coll2 = getCollection(NestedRepeatedAttributeName.class, String.class);
+
+        Calendar cal = Calendar.getInstance();
+        cal.set(0, 0, 0, 0, 0, 10);
+        Date d_1 = cal.getTime();
```
Comment (benmccann) [inline src/test/java/org/mongojack/TestDBUpdateSerialization.java]: `_` is kind of uncommon in Java naming. I'd probably just call them `d1` and `d2`

File: src/test/java/org/mongojack/TestDBUpdateSerialization.java [hunk 8]
```diff
@@ -153,6 +157,30 @@ public void testSimpleMap() {
...
+        cal.set(0, 0, 0, 0, 0, 20);
+        Date d_2 = cal.getTime();
+    	
+        NestedRepeatedAttributeName nested = new NestedRepeatedAttributeName();
+        nested.inner.timestamp = d_1;
```
Comment (benmccann) [inline src/test/java/org/mongojack/TestDBUpdateSerialization.java]: `nested` is a pretty confusing name because it means essentially the same thing as `inner`, which isn't what you mean at all. How about if we just call it `obj` instead?

**Comment by tbartley** [comment]
Thanks again. Went with 'original' oveer 'obj' since that's a clearer meaning and makes sense in the comparison. And I've removed the underscores.

File: src/test/java/org/mongojack/TestDBUpdateSerialization.java [hunk 9]
```diff
@@ -153,6 +157,30 @@ public void testSimpleMap() {
...
     }
 
+    // Test to detect presence of issue https://github.com/devbliss/mongojack/issues/98
+    @Test
+    public void testUpdateOfNestedRepeatedAttributeName() {
+        coll2 = getCollection(NestedRepeatedAttributeName.class, String.class);
+
+        Calendar cal = Calendar.getInstance();
+        cal.set(0, 0, 0, 0, 0, 10);
+        Date d1 = cal.getTime();
```
Comment (benmccann) [inline src/test/java/org/mongojack/TestDBUpdateSerialization.java]: What if you just did:

    Date d1 = new Date(10_000l);

It doesn't really matter what the date is and that'd be fewer lines of code, which I think makes the test more readable

**Comment by benmccann** [comment]
Looks great! Sorry, just one last comment. And also, do you mind squashing the commits?

File: src/test/java/org/mongojack/TestDBUpdateSerialization.java (hunk 9 above)
Comment (tbartley) [inline src/test/java/org/mongojack/TestDBUpdateSerialization.java]: Agreed - something made me think there wasn't a Date(long) constructor.

**Comment by tbartley** [comment]
Done.
